# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run prettier

      - name: Test
        run: npm t

      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
